### ISSUE TITLE
FloatBorder is same color as background, making it invisible

### ISSUE THREAD

**Issue by AjiBuster499** [AlphaTechnolog/everblush.nvim#10]
My screenshot tool is acting up so I can't provide a picture to demonstrate, but when I do `:highlight FloatBorder`, I can see that the foreground color (or whatever the text color is), is the same as the background, which renders it invisible.

EDIT: I got the highlight group wrong.

**Comment by mngshm** [comment]
Is FloatBorder particularly from some plugin?

**Comment by AjiBuster499** [comment]
I believe it is from just the LSP. It's the little border around hover windows (i.e. documentation).

**Comment by mngshm** [comment]
Ok I'll check

**Comment by AjiBuster499** [comment]
I opened a PR to fix this, since it was simpler than I thought.

I've never looked into the code behind colorschemes before so was a bit scared, but it's simpler than I thought it'd be.

**Comment by mngshm** [comment]
Great! You can always do it
