### ISSUE TITLE
Use nvim-treesitter's new highlighting groups

### ISSUE THREAD

**Issue by karimudev** [AlphaTechnolog/everblush.nvim#15]
Hello,

I just tried to install the everblush colorscheme for Neovim. However, the colors look completely different from the preview image in the README, as you can see below.

<img src="https://user-images.githubusercontent.com/87835614/200662004-d17cc094-d64a-4e64-ad29-3a1bc839d4e8.png" width = 60% />

The issue seems to be related to the following breaking change in nvim-treesitter: https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1279974776
The "TS" highlighting groups have been rendered obsolete, and this is what causes the issue for me.

I have solved the issue for my own config, using this temporary fix I found online: https://gist.github.com/rockerBOO/be0770242db9b7215b8e83e135516a65
However, this is more of a band-aid rather than a true fix!

**Comment by diniamo** [comment]
I've already been working on this, your snippet might be useful though.

**Comment by diniamo** [comment]
As you can see, I made the PR, I would appreciate if you looked at it.
