### ISSUE TITLE
Request for License for Nightly.nvim Repository

### ISSUE THREAD

**Issue by Alexis12119** [AlphaTechnolog/everblush.nvim#22]
I recently created a GitHub repository called [Nightly.nvim](https://github.com/Alexis12119/nightly.nvim) based on the Everblush theme created by your team. I really like the colors of the theme and wanted to create a customized version of it for my own use.

However, I want to ensure that I'm following the proper licensing requirements. I have included a credit to your team and a link to the original theme in the README file of my repository. But I understand that this may not be sufficient without a proper license.

Could you please add a license to the Everblush theme, or provide me with permission to use the theme in my repository with the appropriate license? If I'm not allowed to create a customized theme based on your theme, then I'll delete the repo.

Thank you for your time and I look forward to your response.

**Comment by samuelnihbos** [comment]
I've added the license as per [9a0e695](https://github.com/Everblush/nvim/commit/9a0e695fdd57b340d3ba2b72406e3ca519029f25) commit. Thank you for reminding us to put a proper license to this project!

**Comment by mngshm** [comment]
Can I see a screenshot of your modified version of Everblush?

**Comment by Alexis12119** [comment]
Sure, here's the link of the reddit post.

https://www.reddit.com/r/neovim/comments/13efti8/customized_everblush_theme/

Most of my changes are just for visibilty things.

**Comment by Alexis12119** [comment]
Sure

![Screenshot (478)](https://github.com/Everblush/nvim/assets/74944536/cea5880b-e1a6-49a9-b2a8-ab1a6e4de17a)

![Screenshot (483)](https://github.com/Everblush/nvim/assets/74944536/e16f3bc4-43d3-4716-a950-7bae9dfece69)

![Screenshot (512)](https://github.com/Everblush/nvim/assets/74944536/eabe2e30-f203-4df8-ae52-be21873bb9ac)

![Screenshot (518)](https://github.com/Everblush/nvim/assets/74944536/8f071456-1508-4eeb-95dd-e4b5dc3d1c1d)

**Comment by Alexis12119** [comment]
I just made some modifications.

**Comment by mngshm** [comment]
It looks pretty similar tho, :) But it's ok until you enjoy using it!
