### ISSUE TITLE
Neogit coloring makes diffs unreadable

### ISSUE THREAD

**Issue by sschneemelcher** [AlphaTechnolog/everblush.nvim#4]
In Neogit, the diffs are unreadable as the foreground and background colors are the same. Also the highlighted hunk is a bit hard to read.
<img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/46780643/181009998-06362b4d-f4cd-46a5-8150-68f142ec9e72.png">

I already fixed it for me (see second screenshot) and could provide a PR. Also, I have seen that the repository has no license yet, which should be changed to allow cooperation.
<img width="1440" alt="Screenshot2" src="https://user-images.githubusercontent.com/46780643/181010594-f9556738-ec95-4ccb-a4b6-d0649f55cbda.png">

Let me know what you think 😃

**Comment by mngshm** [comment]
nice, you can surely do the PR.
